<?php
/**
 * AdminDeselectRadios - A module for ProcessWire
 *
 * Allows admin radio selects to be deselected.
 *
 * @author tpr, Netcarver
 *
 * ProcessWire 2.x
 * Copyright (C) 2011 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class AdminDeselectRadios extends WireData implements Module {

	public static function getModuleInfo() {
		return array(
			'title'     => 'AdminDeselectRadios',
			'class'     => 'AdminDeselectRadios',
			'version'   => '1.0.1',
			'summary'   => __('Allows admin radio selects to be deselected.'),
			'href'      => 'https://processwire.com/talk/topic/12987-uncheck-checked-radio-buttons-in-admin/#entry117744',
			'author'    => 'tpr, netcarver',
			'autoload'  => 'template=admin',
			'singular'  => true,
			'permanent' => false,
		);
	}


	public function init() {
        	$root = $this->config->urls->siteModules.__CLASS__;
		$this->config->scripts->add($root."/AdminDeselectRadios.js");
	}
}
